### ISSUE TITLE
GetRequestToken on Windows Store App

### ISSUE THREAD

**Issue by agentKnipe** [Yortw/tweetmoasharp#10]
I pulled down your package from NuGet for use in a windows store app.  I tested it with my test console and everything works great.  When I added the package to the windows store app I am getting an error indicating GetRequestToken() requires at least 1 parameter, which doesnt seem to be required in my test use of the package.

**Comment by Yortw** [comment]
Hi, 

Sorry for the delayed reply. Are you getting this as a compile or runtime error? Could you perhaps provide some sample code?

I have just created a brand new Windows 8.1 universal app, and put this code into the app.cs constructor, and it works fine - compiles, and I get a request token back;

			TweetSharp.TwitterService ts = new TweetSharp.TwitterService("xxxx", "yyy");
			ts.GetRequestToken((t, r) =>
			{
				var e = r.Error;
			});

My only guess is that you are not providing a call back delegate to the GetRequestToken function. On Windows 8 and Windows Phone 8 all synchronous methods are removed (to ensure synchronous methods aren't called on the UI thread). In the console app, there will be an overload that runs synchronously and returns the token, which is why the console app works with no arguments.

There is no overload of GetRequestToken in the WinRT library that just returns a value, because it would block the calling thread and that's not allowed. Therefore you must choose one of the asynchronous methods. Normally there are three choices to choose from;

1. BeginXXX with an subsequent EndXXX call
2. XXX(callback delegate)
3. await XXXAsync

However it appears some of the auth methods, in particular GetRequestToken, only support the second style above. For those methods you pass a delegate or lambda expression that is executed when the result (in this case token) is retrieved. The callback is passed the response status and the token value as arguments. This is done to ensure the that if multiple async calls are made simultaneously you don't lose or confuse the response values. In my sample above, 't' is the token value and 'r' is the response value passed to the callback.

My suggestion for WinRT dev would be;

1. For GetRequestToken and any other method that doesn't have a tasked based Async version, use the callback verison.

2. For everything else, use async/await with the methods that end with the word Async. That will let you write code that look synchronous and is slightly easier to reason about, but is really async and doesn't block the calling thread.

**Comment by Yortw** [comment]
Since there's no response, and I feel the problem is probably just a need to use the async methods, I'm closing this issue. Please let me know if you're still having problems.
