### ISSUE TITLE
Problem with UAP?

### ISSUE THREAD

**Issue by MysticEmpires** [Yortw/tweetmoasharp#17]
Hi,

is there a problem with UAP again? If i create a NEW App. Download only tweetmoasharp with nuget go to the "MainPage.xaml.cs" und use this function. The App never comes the line with "returnval = ....". So it looks like SearchAsync got a problem :/.

public static async Task<List<TwitterStatus>> GetTestTweets()
{
    var returnval = new List<TwitterStatus>();

    try
    {
        var service = new TwitterService(ConsumerKey, ConsumerSecret);
        service.AuthenticateWith(AccessToken, AccessTokenSecret);

        var results = await service.SearchAsync(new SearchOptions { Q = "#test", Count = 50 });
        returnval = new List<TwitterStatus>(results.Value.Statuses);
    }
    catch (Exception exc)
    {
        System.Diagnostics.Debug.WriteLine(exc.Message);
    }

    return returnval;
}

The same code works very well on a normal WPF or Command Line-Application.

**Comment by Yortw** [comment]
Yes unfortunately, and I do not know when I'll be able to fix it. I spent 8 hours looking at it Sunday and got nowhere. The same binary/code seems to work fine under WinRT but has stopped working on UWP.

There appear to be two problems. First, errors in deserialisation don't get reported back to the caller. I am not sure why, I spent the least amount of time on this.

The second (and root) problem appears to be the response stream is not be automatically decompressed. There are no settings on the UWP version of HttpWebResponse that control decompression (at least that I can find). It was working, seems to still work for WinRT, but no longer works in UWP and I don't know why. I presume it is a bug in TweetMoaSharp/Hammock rather than something in the UWP runtime changing, but I can't find it. I tried hacking it temporarily by implementing the manual decompression used for the Silverlight platform, but that isn't possible because the UWP version of HttpWebResponse isn't inhertiable so would require a massive refactor of Hammock to make it work.

I intend to look again sometime, but not sure when, and not sure how long it will take. If you'd care to take a look yourself, I'd appreciate the help.

Thanks, and sorry for the inconvenience.

**Comment by MysticEmpires** [comment]
Mh thats a bit "funny" because the v3.0.0.6 works very well some weeks ago. 

Now the v3.0.0.6 and v3.0.0.9 does not work. Seems like a change in the nativ code of Windows 10. I have actual not older Windows 10 Build to try it. Otherwise i have no idear why a working build (v3.0.0.6) should stop work without a change (or nuget Update).

**Comment by Yortw** [comment]
Thanks for confirming that. I was sure it used to work and I was just going crazy! I'll keep looking into it, but as you say, old builds no longer work when they used to so circumstantially it may be out of my control :sad:

**Comment by Yortw** [comment]
So I can confirm 3.0.0.6 works in a WinRT 8.1 project and fails in a UWP project. I *thought* it previously worked in a UWP project, but it's impossible to test now. The problem seems to be the json deserialisation fails because it is passed the compressed response, not the uncompressed one.

I've contacted someone at MS on the UWP team, hopefully they can shed some light.

**Comment by MysticEmpires** [comment]
I can 100% confirm that the 3.0.0.6 works very will in UWP some weeks ago. I worked very often on my App at this time with this Version of tweetmoasharp.

**Comment by Yortw** [comment]
I could probably produce a version for UWP that doesn't use compressed responses, but I'm loath to do so as it's a large and silent inefficiency. I'd rather find a way to make it work at this point.

**Comment by MysticEmpires** [comment]
There is an Update for "Microsoft.NETCore.UniversalWindowsPlatform" to 5.0.1-beta-23225. Maybe it fix the problem interal. But i could test ist because the nuget update fail (and i dono why :/)

**Comment by Yortw** [comment]
So two lots of good news;

Microsoft are being very helpful trying to determine what the issue is. They can't see why there would be a problem so have asked for a sample project that reproduces the issue, which I've just shared with them tonight. I also learned this problem disappears if you run the UWP app traffic through Fiddler, so it would appear something is messing with the requests. Hopefully MS can provide more detail.

The better news is I figured out a way to implement gzip compression in WinRT and UWP (it wasn't that hard once I looked at it with a clear head). The code is a little ugly, but it works, so I've pushed an update to nuget.

Please try nuget package version v3.0.0.10 and see if that solves your issue.

Thanks.

**Comment by Yortw** [comment]
Thanks for letting me know :+1:

**Comment by Yortw** [comment]
The exceedingly helpful people at Microsoft have determined what the issue is. It seems Twitter *always* sends a gzip response to requests made via the HTTP/2 protocol, regardless of the accept headers used. Not sure if that's a bug, or a reasonable thing to do (HTTP/2 may well specify compression as part of the protocol, since it's design is largely about improved performance). The UWP framework uses new networking components that use HTTP/2 by default, while WinRT still uses older ones. Additionally, if you run the traffic through a proxy (like Fiddler) and the request is downgraded to HTTP/1.1, then it works because Twitter obeys the accept encodings again.

Anyway, the change I made should be a good permanent fix, but nice to know what was going on and why.

**Comment by MysticEmpires** [comment]
It's a very nice behavior from MS to help here that fast and that detailed.

But im also wonder why it's break some days after v3.0.0.6. Is this a change by Twitter? Because we change nothing and the UWP does also not changed also.

Is there a nice way to report a "Bug" to Twitter?

**Comment by Yortw** [comment]
Yes, I believe the Twitter end changed. I assume they used to respect the accept endoing header even on http/2, and have changed something so now that is not true.

**Comment by davidsh** [comment]
@Yortw The pre-draft version of HTTP/2.0 which was called SPDY always sent compressed content. I believe that Twitter used to support the older SPDY before it moved to the official HTTP/2.0.  SPDY required the client to be able to accept gzip by default regardless of any request headers.  But the final HTTP/2.0 does not do this.  So, perhaps this SPDY behavior of always sending compressed content is still present in the server implementation.

**Comment by Yortw** [comment]
Hi @davidsh - Thanks for dropping by and leaving this detial :smile:  Good to know what the standards/specifications are.

The only problem with the theory that this is 'left over from when Twitter supported SPDY' is that it appears to have worked about 4 weeks ago (i.e they obeyed the accept headers), and then stopped working in the last week or two. So it would appear they used to do the right thing, and then stopped, and since HTTP/2 is newer than SPDY it doesn't seem like it's just 'left over' behaviour. Unless the UWP bits have changed recently so HTTP/2 is always used but wasn't previously? I suspect that isn't true, and that UWP has used HTTP/2 since release?

Thanks for the detail though, helpful.

**Comment by davidsh** [comment]
UWP networking stack (Windows 10 systems) will always try by default to use HTTP/2.0 when communicating with HTTP servers.  I can't explain the behavior of the Twitter server and when it worked or didn't work.  But it is possible that prior connections might have been going thru a proxy server which means it might not have been talking HTTP/2.0 in the first place when you observed decompressed content being received.
