### ISSUE TITLE
TweetSharp vs Tweetmoasharp

### ISSUE THREAD

**Issue by kiquenet** [Yortw/tweetmoasharp#18]
Newbie using Twitter with those targets and questions:

Which latest API Twitter ?
Limitations for get tweets, download images, etc ?
How can I get your all tweets list ?
And download photos and videos from anyone timeline too ?
How get the list of followers and following ?
How send DM anyone user ?
How can I follow to user ?
How manage lists ?
How get favorites lists ?

I want to do it programmatically using C# but for .NET, I have not seen many samples official Twitter:
NOw, I have found 2 API: TweetSharp vs Tweetmoasharp
https://github.com/danielcrenna/tweetsharp
https://github.com/Yortw/tweetmoasharp/

Which is the recommended ? Can I do all my targets ?

Mindly notes:

Any good getting started with Tweetmoasharp? step by step in 10 minutes?

IMHO, better samples for minimize learning curve are real applications with full source code and good  patterns and practices

Full source code sample REAL application? not Demo, only real applications?
Like for small to medium applications development, but open source, if you can sharing or maybe another real project or production-ready application using.

main influences, are full of innovative ideas that can free our minds to explore new techniques, patterns and paradigms.

You want to use technologies that allow for rapid development, constant iteration, maximal efficiency, speed, robustness and more. You want to be lean and you want to be agile. You want to use technologies that will help you succeed in the short and long term. And those technologies are not always easy to pick out.

Mindly notes 2

Why not working together ?

https://tweetinvi.codeplex.com/90
https://www.nuget.org/packages/TweetinviAPI45

https://linqtotwitter.codeplex.com/36
https://www.nuget.org/packages/linqtotwitter28

https://github.com/opentig/TwitterIrcGateway30

https://github.com/danielcrenna/tweetsharp
https://github.com/Yortw/tweetmoasharp/

**Comment by Yortw** [comment]
Hi,

Thanks for providing feedback, it is always valuable. I'm glad to see someone excited about a new project and considering using TweetMoaSharp.

Before I go any futher, can I perhaps suggest you consider LinqToTwitter? It's been a long time since I looked, but I believe they have better documentation & samples as well as a larger community who are more likely to be able to help you with questions. 

With regards you your specific questions and TweetSharp/TweetMoaSharp;

*Which latest API Twitter ?*
As mentioned in the readme files, TweetSharp is no longer maintained or supported and hasn't been from sometime. TweetMoaSharp is a fork of TweetSharp that I am currently maintaining mostly on my own. As a result, TweetMoaSharp is the 'newer' one and will support the newer API's. However nobody guarantees all the latest Twitter features are neccesarily available. You'll need to check the methods on the TwitterService object in the library to see what is supported.

You should defintely use either TweetMoaSharp or "TweetSharpUnofficial" as opposed to the original TweetSharp. The original TweetSharp nuget package has known problems due to changes in the Twitter API over the last few years, and building the source is non-trivial for most people.

*Limitations for get tweets, download images, etc ?*
There are no imposed limits in TweetSharp/TweetMoaSharp that I'm aware of. However Twitter imposes various different limits all over their API. We haven't, and don't intend to document these here. Twitter can change the rules at any time, and generally update their own documentation. Having us document those limits here doubles up on the effort of documenting them, creates more work for us, and is likely to mean our docs are constantly out of date. Twitter's main limit is the 'api rate limit' which restricts the number of calls your app can make within a time period. TweetSharp/TweetMoaSharp return information about your current rate limits after every Twitter request, so you can code your application to cope. The readme file contains a brief section on the rate limiting stuff. TweetMoaSharp can also make a request to Twitter to get some dynamic limits programmatically, such as the 'length of all url's in Tweets' and the 'number of media per tweet' etc. For other limits, the GetRetweet method which only returns up to 100 retweets you'll need to read the Twitter docs. 

*And download photos and videos from anyone timeline too ?
 How get the list of followers and following ?
 How send DM anyone user ?
 How can I follow to user ?
 How manage lists ?
 How get favorites lists ?*
As the readme file says, 

From the readme file:
*TweetSharp uses a consistent method naming convention to help you locate the method you're looking for. In general, methods that return multiple results begin with  List , while methods that return a single result begin with  Get . Most methods, like the Twitter API, have additional parameters for obtaining pages of results rather than the default count. Keep in mind that paging methods have limits that you can confirm at (http://dev.twitter.com)*

Basically, you need to check the Twitter API to see what is possible and how to use it. Once you know that, it should be very easy to find appropriate method on the TwitterService object in TweetMoaSharp and the call should be self-explantory (or at least understandable from the Twitter docs).

*Any good getting started with Tweetmoasharp? step by step in 10 minutes?*
Only what is in the readme file. Apart from that, no, sorry. My spare time is precious and I get very little out of maintaining TweetMoaSharp, and *almost* no one contributes code/time towards helping. The spare time I do spend on TweetMoaSharp is spent fixing bugs and adding features. The library is published under a good will system - if it's useful to you great, if not you're welcome to find something else, if you want to contribute that would be fantastic. I do not get paid for this, it is not really a labour of love and I'm not seeking fame. Using TweetMoaSharp should be drastically easier than trying to access Twitter without any kind of library. It may or may not be the best library for any given project. If it's too hard or too much investment for people to figure out how to use the library, then those people should find something which is a better fit (perhaps LinqToTwitter).

*IMHO, better samples for minimize learning curve are real applications with full source code and good patterns and practices*
As above, my time is precious, I do not require this, and there is no benefit to me for the cost of spending the time to make these. If you would like to do so and contribute them, I would be delighted to add them to the repo. I'll even figure out how to grant you direct access to the Wiki so you can add them yourself if you like. It is not something I intend to do myself in the forseeable future however.

*Full source code sample REAL application? not Demo, only real applications?
 Like for small to medium applications development, but open source, if you can sharing or maybe another real project or production-ready application using.*
There is **considerable** effort in building such applications, and again, no real benefit to myself. I'm not against helping people out where I can, but I do not have time for this. Also, what kind of applications? Windows Phone? Console apps? Web sites? Desktop apps? Silverlight? All of the above? Wayyyy too much effort, and would likely lead to a bunch of 'copy cat' apps in the app stores. I don't really want to be responsible for that either. I'm not here to build other peoples apps for them, and everyone disagrees on how to build apps anyway. Also, real world production apps often aren't the best learning tools - people get stuck on depdency injection, inversion of control and MVVM long before they get to the meaty parts like dealing with Twitter. Everyone is at a different stage of learning,  a full production app would be too much for many people.

*You want to use technologies that allow for rapid development, constant iteration, maximal efficiency, speed, robustness and more.*
Yes, and it is my sincere hope that TweetMoaSharp provides those things over doing everything yourself. That doesn't mean no investment at all is neccesary on the part of the developer consuming it.

"Why not working together ?"
Why is there Windows, Linux and MacOSX? Why Windows Phone, iOS and Android? Why C#, Swift, Objective-C, C++, Java, F#, Haskell etc. ? Why Ford and GMS? 

People value different things, they have different goals, and different ways of achieving them. Also, many of these things are produced at different times, when different technology is available, or different patterns are popular. TweetSharp for example, doesn't force you to use Linq, which means it can work quite nicely on .Net 2.0 which some enterprise users are stuck on. I am not sure if LinqToTwitter can claim the same, since it is heavily based on LINQ which came out after .Net 2.  There are probably hundreds, if not thousands of other differences. Those differences drive innovation and new ideas, and give devs choice. Hopefully that choice means they can find a library that is a great (or at least good) fit for them, rather than be stuck with the "one framework to rule them all(TM)" which serves everyone poorly.

I'm sure the devs working on those other projects are great guys, but I've never actually spoken to them. We're each doing our own thing, solving our own problem for our own reasons and publishign the result in case it's useful. 

Good luck with your project. If you have a specific question, with a code sample or error message etc. then please post again and I'll help if I can.

**Comment by Yortw** [comment]
Hi,

Thanks for the suggestion, but I stand by my previous responses.

I am not Microsoft, I do not have their resources. I do not have the time or inclination to provide a 'real app', nor did the original author. Further, I no longer have any real apps of my own using this library. Any support at all provided now is purely out of love for the community, I have no personal interest or benefit in this project.

I am happy to accept pull requests if someone else wants to make a 'real app' (whatever that might be, for whatever platform(s) might be wanted), but I do not personally have the time. 

Besides, the very Microsoft samples you point to show general app architecture and patterns, and the TweetMoaSharp examples show how to use the library. For anyone with the time/inclination to build a real app those should provide sufficient resources to get started. I don't see what value a specific app for TweetMoaSharp provides other than bootstrapping other peoples projects... and that assumes the demo app is a version of what they want to build (I assume Twitter client is the request here, but not all Twitter apps are generalised clients).

If you'd like to build the demo app and submit a PR, I'll gladly review and include if it's appropriate.

Thanks again.
