### ISSUE TITLE
JSON parsing error with ListSuggestedUsers?

### ISSUE THREAD

**Issue by aeldaher** [Yortw/tweetmoasharp#21]
Hi -

This snippet crashes with a JSON error. 

ListSuggestedUsersOptions opt = new ListSuggestedUsersOptions();
opt.Lang = "en";
var c = service.ListSuggestedUsers(opt);

Thank you!

**Comment by Yortw** [comment]
I can confirm this error occurs with this snippet. I'm not familiar with these functions (they are part of the original TweetSharp and I haven't yet had to use or modify them), however I have taken a look...

ListSuggestedUsers in TweetSharp is designed to return an actual list of users for a particular 'slug' and optiona language. It uses the Twitter API end point 'https://api.twitter.com/1.1/users/suggestions.json' (https://dev.twitter.com/rest/reference/get/users/suggestions). This endpoint has multiple purposes. When called *with a slug* it returns a list of users which will be deserialised correctly by TweetMoaSharp. However, when called without a slug the endpoint returns a 'collection' of categories (which is actually a collection of TwitterUserSuggestions objects without the users collection filled in).  The TweetMoaSharp function ListSuggestedUserCategories actually calls the endpoint this way and deserialises/returns the correct result.

The deserialisation error occurs because without a slug the method returns multiple values, whereas with a slug it returns one. In the sample code provided there is no slug provided so the system can't deserialise the multiple results into a single ListSuggestedUserCategories method.

To get your sample to work, you either must include a slug value in the call, or use the the ListSuggestedUserCategories method to get a list of valid slugs first. It does not appear Twitter itself allows you to get suggested users without a slug.

Technically the bug in TweetSharp/TweetMoaSharp is that ListSuggestedUsers doesn't throw an explicit exception requiring the slug to be non null and non empty. Fixing that would be a good idea, but the templating system used to generate these methods doesn't have any ability to do that and it's considerable effort to add for this one use case. I may fix it in the future but I don't have time right now, and since it would only provide a better error message and not missing/broken functionality I don't consider is a priority. Happy to take a PR if you or someone else wants to have a go though.

**Comment by aeldaher** [comment]
All right - thanks for looking into it. I noticed the word "slug" but I had no idea what it meant. I'll change my client code to first fetch the categories, thanks again!

**Comment by Yortw** [comment]
No problem. I had no idea about slug either until I investigated.
Let me know if you have any issues with using those methods with these new tips.

Thanks.
