### ISSUE TITLE
No submodule mapping found for path 'hammock' ?

### ISSUE THREAD

**Issue by c-w-n** [Yortw/tweetmoasharp#23]

**Comment by Yortw** [comment]
Yes, I believe the original TweetSharp author gave up on having it as a sub-module and just included it in the TweetSharp repository (I think I read an issue or change log to this effect ages ago). 

I've never bothered trying to sort it out because I am not, and don't intend to ship this copy of Hammock separately (in fact I would replace it in TweetMoaSharp with HttpClient if they were closer matches for each other). Since I'm not maintaining/shipping it separately I haven't found the need to figure out git sub modules.

If it's causing a problem, or you want to attempt a PR (can you do this to fix the submodule issue?) then I'm happy to look at it as time allows.

I'm not sure when/why you're getting that error message. Perhaps if you elaborate a bit more I can help.
