### ISSUE TITLE
Incompatibility with Newtonsoft.json.dll 7

### ISSUE THREAD

**Issue by AlfonsoML** [Yortw/tweetmoasharp#24]
I've tried to use the 4.0 dll in a project where we have upgraded to 4.0 because a new dll requires Newtonsoft.json.dll with the latest 7.0 version.
Unfortunately that causes an error trying to use the released dll

> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

I've managed to get the sources and compile just the project that I need with the updated dll, but I think that it would be great if you could push a new release compatible with the 7.0 version.

Thank you.

**Comment by Yortw** [comment]
The difficulty is last time I pushed a release that relied on 7.0 I got complaints from another user who couldn't upgraed to 7 due to other issues (and I had to downgrade again). Also, 6.0.0.8 or something is the last version that I can make work properly with the WinRT/UWP platforms (though I believe it is possible to have different references just for those projects).

I'll have to do some research on this and try to figure out what the right answer is, given that just upgrading to 7 has it's own issues.

Thanks for leting me know.

**Comment by kiquenet** [comment]
Maybe, you can use assembly redirect (runtime section) in App.config.

**Comment by AlfonsoML** [comment]
In my case I've compiled and it works so I don't have to mess with this issue again, but as more and more people upgrade their newtonsoft copies it seems that the logical step is to update also the one used here and those that require the 6.0 version can keep using also the older version of this dll. 

That way everybody wins.

**Comment by Yortw** [comment]
I agree something needs to be done, just not sure what.
Assembly rediect is a good suggestion perhaps (thanks), but not sure if I can modify app.config from nuget package (especially in Nuget 3 where some features like PS scripts have been dropped from the older verisons).

**Comment by Yortw** [comment]
I've published a new version (3.0.0.13) that should use the latest json.net (8.01) for .Net 4/4.5(x) projects. Let me know if that helps or not. 

UWP/WinRT stil use 6.08 because I believe there are issues using the newer packages with those frameworks, and WP/SL are still stuck at 5.something because I believe those were the last supported versions.

**Comment by Yortw** [comment]
Anyone tried the new build yet?

**Comment by Yortw** [comment]
Assuming this is fixed by the latest update, since no one has replied. Can be reopened if this is not the case.
