### ISSUE TITLE
No Media being returned using ListTweetsOnUserTimeline

### ISSUE THREAD

**Issue by christophermacdee** [Yortw/tweetmoasharp#75]
Currently on v4.0.3 of the package and there are no Media being returned under the Entities for each tweet.

I can't update to latest package version as I have another package that restricts me updating my Newtonsoft.Json package. Is this due to a change in Twitter API?

Thanks,
Chris MacDonald

**Comment by Yortw** [comment]
Hi,

Very sorry it's taken me so long to get back to you.
I've just run a test and I definitely get some media appearing in the Entities.Media collection (for at least some tweets) when calling methods like ListTweetsOnHomeTimeline. From memory (and it's been a while since I worked on this), some media doesn't show up in the media collection (IIRC correctly animated gifs and images where more than one image was attached to a tweet). You should be able to find the other media types in the *ExtendedEntities* property of the tweet. Also make sure the *IncludeEntities* property of the service isn't set to false for some reason.

Also, I added a *MergeMultiplePhotos* property to *JsonSerializer*. If you create your own instance of the serializer, set that property to true and pass it to the *TwitterService* instance you're using, then it will put additional still images from *ExtendedEntities* into the normal Entities.Media collection, so there's a single source, but you may still need to use *ExtendedEntities* for video/animated gifs etc.

If you are still having problems, please provide the id of a tweet that has the issue and I'll see if I can debug based on that sample.

Thanks.

**Comment by Yortw** [comment]
PS: Are you not able to use a binding redirect to work around the dependency issue?

**Comment by christophermacdee** [comment]
Hi Troy,

Thanks for getting back in touch. We ended up using Juicer to manage
multiple accounts and we created an API wrapper to use that instead. Sure
it was probably a configuration issue on my end.

Many thanks,
Chris

**Comment by Yortw** [comment]
Probably the same as #79.
