### ISSUE TITLE
No search option for "tweet_mode : extended"

### ISSUE THREAD

**Issue by nszeitli** [Yortw/tweetmoasharp#78]
` SearchOptions searchOptions = new SearchOptions {Q = "$btc", Count = 50, Lang = "en" };
            TwitterSearchResult result = _service.Search(searchOptions);`

Search results will only have 140 chars max in text. SearchOptions needs the new tweet_mode parameter for the API, unless I am missing something?

**Comment by Yortw** [comment]
Hi,

It's been a while since I worked on this and I'm not in a position to test/check right now, but I think this was implemented on TwitterService as a 'global' setting (per service instance), rather than having to pass it on every call. Should be a property called something like *TweetMode* on the TwitterService instance you can set. Can you try that and see if it works for you?

Thanks.

**Comment by nszeitli** [comment]
Yep that works, thanks for the help.

**Comment by TobiasVdb** [comment]
Where do I find this TweetMode? I don't see it on the TwitterService version 2.3.1 @nszeitli @Yortw
